### ISSUE TITLE
Deco Dojo

### ISSUE THREAD

**Issue by KingKatanova** [Son-Guhun/Titan-Land-Lands-of-Plenty#157]
[ ] - https://www.hiveworkshop.com/threads/dojo-doodad-pack.292002/ (Minus floor tiles, i know they allready exist)
[ ] - https://www.hiveworkshop.com/threads/wooden-bridges.292602/
[ ] - https://www.hiveworkshop.com/threads/pandarentemple01.220886/#resource-33157
[ ] - https://www.hiveworkshop.com/threads/pandarian-hut-shelter.308292/
[ ] - https://www.hiveworkshop.com/threads/pandarian-hall-research-center.308294/
[ ] - https://www.hiveworkshop.com/threads/pandarian-sanctuary-advanced-research-center.308296/
[ ] - https://www.hiveworkshop.com/threads/pandarian-wall-wall-enhanced-wall.312348/
[ ] - https://www.hiveworkshop.com/threads/pandarian-energy-spire-energy-spire.312366/
[ ] - https://www.hiveworkshop.com/threads/pandarian-elemental-shrine-element-well.312368/
[ ] - https://www.hiveworkshop.com/threads/japanese-house.292667/#resource-72048
[ ] - https://www.hiveworkshop.com/threads/japanese-arc.266166/#resource-70409
[ ] - https://www.hiveworkshop.com/threads/japanese-cherry-tree.48324/#resource-21286 (although would be better in trees)
[ ] - https://www.hiveworkshop.com/threads/paper-lanterns.292853/#resource-75445
[ ] - https://www.hiveworkshop.com/threads/bamboo.233143/#resource-34405 (likewise, better in trees)
[ ] - https://www.hiveworkshop.com/threads/destructibleeasternarchway-by-callahan.188635/
[ ] - https://www.hiveworkshop.com/threads/nightelftower.47948/

**Comment by Son-Guhun** [comment]
The Dojo and Panderen models were already planned as Forest Elf decorations, to match their buildings. The relevant issue is here: https://github.com/Son-Guhun/Titan-Land-Lands-of-Plenty/issues/77

The other ones are not planned though, so I will mark as duplicate and keep open.
