### ISSUE TITLE
Remove Vanilla Ancients

### ISSUE THREAD

**Issue by Son-Guhun** [Son-Guhun/Titan-Land-Lands-of-Plenty#164]
Ancients are used as a special type of unit, not a structure. Therefore, they should not be converted into a decoration.

If one wants to use a rooted ancient with flying height, they can simply give an unrooted ancient the alternate tag.

**Comment by KingKatanova** [comment]
I dont see an issue having the ancient model as both a unit/structure and a deco? as a unit they cannot be heighted by a minus value or more importantly cannot be raised by the x-y-z values individually, they are also very difficult to place around a build when acting as just a unit.

**Comment by Son-Guhun** [comment]
Having both versions would break the  "No duplicate models" policy. It would also mean for each classic, reforged and custom ancient, 2 units would be required, which could easily generate an extra 20~30 units. The policy is not broken for normal structures since the plan is to completely get rid of them and keep just the decoration version, but the same can't be done for Ancients (because they need to move).

Since they are not bound to the 64x64 grid while unrooted, they can at least be moved precisely using the Deco Modifier Controller, unlike normal buildings, so you can still place them pretty precisely if the need arises.

Negative height/pitch/roll/dimensional sizing are just limitations of the engine right now. I don't think it's enough to justify creating a decoration alternative for every unit model, so the same extends to Ancients. Blizzard's already added ways to allow them for normal units, they are just bugged and don't work. Even if they never get around to fixing them, I could work around those limitations myself with enough time.

**Comment by KingKatanova** [comment]
i see your point, now that leaves the vanilla night elf a little open right now, potential to add
-barrow den
-den of secrets (its a beta model, custom model would have to be aquired)
-horn of cenarius
-night elf fishing village (if not allready been added)
-enchanted gemstone obelisk (if not allready added)

**Comment by Son-Guhun** [comment]
The fishing villages and barrow den are used by the Night Elf race itself, but they can be converted to Decorations. I'll try to get that done for 1.4.0 or 1.4.1.
